"""Refactor meter readings for contract support

Revision ID: 143518295e96
Revises: 2977567de2c8
Create Date: 2026-05-15 23:10:48.328673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143518295e96'
down_revision = '2977567de2c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meter_readings', sa.Column('contract_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('meter_readings', sa.Column('reading_type', sa.Enum('MOVE_IN', 'MONTHLY', 'MOVE_OUT', 'FINAL', name='readingtype'), nullable=True))
    op.add_column('meter_readings', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('meter_readings', sa.Column('period_end', sa.Date(), nullable=True))
    op.add_column('meter_readings', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_meter_readings_contract_id'), 'meter_readings', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'meter_readings', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meter_readings', type_='foreignkey')
    op.drop_index(op.f('ix_meter_readings_contract_id'), table_name='meter_readings')
    op.drop_column('meter_readings', 'is_locked')
    op.drop_column('meter_readings', 'period_end')
    op.drop_column('meter_readings', 'period_start')
    op.drop_column('meter_readings', 'reading_type')
    op.drop_column('meter_readings', 'contract_id')
    # ### end Alembic commands ###
