"""Add contract termination fields and tables

Revision ID: 2977567de2c8
Revises: d0ff584c6da0
Create Date: 2026-05-15 23:04:45.296408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2977567de2c8'
down_revision = 'd0ff584c6da0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('actual_end_date', sa.Date(), nullable=True))
    op.add_column('contracts', sa.Column('cancel_reason', sa.String(length=500), nullable=True))
    op.add_column('contracts', sa.Column('termination_note', sa.Text(), nullable=True))
    op.alter_column('contracts', 'vehicle_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('contracts', 'termination_reason')
    op.alter_column('invoices', 'vehicle_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('invoices', 'old_debt',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.text("'0'::bigint"))
    op.add_column('room_tenants', sa.Column('move_out_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_tenants', 'move_out_reason')
    op.alter_column('invoices', 'old_debt',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.alter_column('invoices', 'vehicle_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('contracts', sa.Column('termination_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('contracts', 'vehicle_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_column('contracts', 'termination_note')
    op.drop_column('contracts', 'cancel_reason')
    op.drop_column('contracts', 'actual_end_date')
    # ### end Alembic commands ###
