"""Add archived_at field for data separation

Revision ID: 746870d4d883
Revises: 143518295e96
Create Date: 2026-05-15 23:26:56.033506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746870d4d883'
down_revision = '143518295e96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('maintenance_requests', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meter_readings', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'archived_at')
    op.drop_column('meter_readings', 'archived_at')
    op.drop_column('maintenance_requests', 'archived_at')
    op.drop_column('invoices', 'archived_at')
    op.drop_column('contracts', 'archived_at')
    # ### end Alembic commands ###
