"""add_tenant_portal_tables

Revision ID: c6905d5ff883
Revises: 746870d4d883
Create Date: 2026-05-16 11:03:48.648643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6905d5ff883'
down_revision = '746870d4d883'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE IF EXISTS complaintstatus CASCADE;')
    op.execute('DROP TYPE IF EXISTS repairstatus CASCADE;')
    op.execute('DROP TYPE IF EXISTS proofstatus CASCADE;')
    
    # Table tenant_otps already exists in DB
    op.create_table('complaints',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', name='complaintstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_contract_id'), 'complaints', ['contract_id'], unique=False)
    op.create_index(op.f('ix_complaints_organization_id'), 'complaints', ['organization_id'], unique=False)
    op.create_table('repair_requests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REJECTED', name='repairstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_requests_contract_id'), 'repair_requests', ['contract_id'], unique=False)
    op.create_index(op.f('ix_repair_requests_organization_id'), 'repair_requests', ['organization_id'], unique=False)
    op.create_table('payment_proofs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='proofstatus', create_type=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_proofs_invoice_id'), 'payment_proofs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_proofs_organization_id'), 'payment_proofs', ['organization_id'], unique=False)
    op.create_table('repair_request_images',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('repair_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['repair_request_id'], ['repair_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_request_images_repair_request_id'), 'repair_request_images', ['repair_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repair_request_images_repair_request_id'), table_name='repair_request_images')
    op.drop_table('repair_request_images')
    op.drop_index(op.f('ix_payment_proofs_organization_id'), table_name='payment_proofs')
    op.drop_index(op.f('ix_payment_proofs_invoice_id'), table_name='payment_proofs')
    op.drop_table('payment_proofs')
    op.drop_index(op.f('ix_repair_requests_organization_id'), table_name='repair_requests')
    op.drop_index(op.f('ix_repair_requests_contract_id'), table_name='repair_requests')
    op.drop_table('repair_requests')
    op.drop_index(op.f('ix_complaints_organization_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_contract_id'), table_name='complaints')
    op.drop_table('complaints')
    # Table tenant_otps already exists in DB
    # ### end Alembic commands ###
